apiVersion: "v1"
kind: "Service"
metadata:
  name: "backend"
  labels:
    {{- include "marys.labels" . | nindent 4 }}
    app.kubernetes.io/name: "backend"
    service: "backend"
spec:
  selector:
    {{- include "marys.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: "backend"
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "backend-deployment"
  labels:
    {{- include "marys.labels" . | nindent 4 }}
    app.kubernetes.io/name: "backend"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "marys.selectorLabels" . | nindent 6}}
      app.kubernetes.io/name: "backend"
  template:
    metadata:
      labels:
        {{- include "marys.labels" . | nindent 8 }}
        app.kubernetes.io/name: "backend"
    spec:
      containers:
        - image: {{ printf "ghcr.io/mary-initial/mary-initial-backend/backend:%s" .Values.backend.image_tag }}
          env:
            - name: "PORT"
              value: "8080"
          name: "backend"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: "ghcr-secret"
