apiVersion: v1
kind: Secret
metadata:
  name: "ghcr-secret"
  labels:
    {{- include "marys.labels" . | nindent 4 }}
type: "kubernetes.io/dockerconfigjson"
data:
  .dockerconfigjson: {{ printf
    "{\"auths\": {\"ghcr.io\": {\"username\": \"%s\", \"password\": \"%s\", \"auth\": \"%s\"}}}"
    .Values.ghcr_username
    .Values.ghcr_token
    (printf "%s:%s" .Values.ghcr_username .Values.ghcr_token | b64enc)
    | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "basic-auth"
  labels:
    {{- include "marys.labels" . | nindent 4 }}
data:
  ".htpasswd": {{ .Values.basic_auth | b64enc | quote }}