apiVersion: "v1"
kind: "Service"
metadata:
  name: "storybook"
  labels:
    {{- include "marys.labels" . | nindent 4 }}
    app.kubernetes.io/name: "storybook"
    service: "storybook"
spec:
  selector:
    {{- include "marys.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: "storybook"
  ports:
    - name: "http"
      port: 8080
      targetPort: 80
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "storybook-deployment"
  labels:
    {{- include "marys.labels" . | nindent 4 }}
    app.kubernetes.io/name: "storybook"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "marys.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: "storybook"
  template:
    metadata:
      labels:
        {{- include "marys.labels" . | nindent 8 }}
        app.kubernetes.io/name: "storybook"
    spec:
      containers:
        - image: "ghcr.io/mary-initial/mary-initial-frontend/storybook:{{.Values.storybook.image_tag}}"
          name: "storybook"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: "ghcr-secret"
