appId               = "app-id"
password            = "password"
ghcr_token          = "ghcr-token"
ghcr_username       = "ghcr-username"
basic_auth          = "basic-auth"
storybook_image_tag = "storybook-image-tag"
image_tag           = "backend-image-tag"
